INSERT INTO id_rol VALUES (1, "SCRUM MASTER");
INSERT INTO id_rol VALUES (3, "TASK OWNER");
INSERT INTO id_rol VALUES (4, "USER");
INSERT INTO id_rol VALUES (5, "REPRESENTATIVE");
INSERT INTO id_rol VALUES (6, "PROCUREMENT");
INSERT INTO id_rol VALUES (7, "LEGALS");
INSERT INTO id_rol VALUES (2, "PROJECT LEADER");